### ISSUE TITLE
enclose with quotes fields that contain single quote

### ISSUE THREAD

**Issue by fibo** [d3/d3-dsv#35]
This is an issue to discuss about a feature request.

I have a row like

    mc0002,McDonald's Acireale Drive,Via Cristoforo Colombo e Via Cefalu'  ,,,37.621493,15.141527,19,087004,mc01

To be able to load it into a database, since some fields contain a single quote, it would be really comfortable if `d3.csvFormatRows` would enclose those fields in doule quotes, like this

    mc0002,"McDonald's Acireale Drive","Via Cristoforo Colombo e Via Cefalu'  ",,,37.621493,15.141527,19,087004,mc01

**Comment by mbostock** [comment]
Sorry for the delayed response. From the perspective of the DSV format, there’s no reason to escape single quotes because they aren’t special characters; they don’t affect parsing. If you’re using some other tool to parse these files that treats single quotes as double quotes, you’ll either need to configure that tool to… not do that, or use a different (or custom) DSV formatter.

**Comment by mbostock** [comment]
d3.csvFormatRows automatically quotes values that needs them—with double quotes. A value with single quotes does not need to be quoted.

**Comment by fibo** [comment]
Many databases will have issues with single quotes, the loading could fail or be truncated. For instance I was working on Redshift. Anyway I already solved my issue using a custom function, thank you for sharing your code.
